2024-12-13 17:38:36,792 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Diana\PycharmProjects\PythonProject1\tests_12_4.py", line 73, in test_run
    runner_2 = Runner(456)
  File "C:\Users\Diana\PycharmProjects\PythonProject1\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-13 17:38:36,795 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Diana\PycharmProjects\PythonProject1\tests_12_4.py", line 63, in test_walk
    runner_1 = Runner('Walya', speed=-4)
  File "C:\Users\Diana\PycharmProjects\PythonProject1\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -4
